repos:
    - repo: https://github.com/psf/black
      rev: '20.8b1'
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v5.7.0'  # Use the revision sha / tag you want to point at
      hooks:
        - id: isort
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v3.4.0'
      hooks:
        - id: check-added-large-files
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: 'v1.16.0'
      hooks:
        - id: setup-cfg-fmt
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0  # Use the ref you want to point at
      hooks:
      - id: trailing-whitespace
      - id: check-yaml
        exclude: docs/mkdocs.yml
    - repo: https://github.com/PyCQA/pylint
      rev: 'pylint-2.6.0'
      hooks:
      - id: pylint
        name: pylint
        entry: pylint mkdocstrings_sourcelink
        language: system
        pass_filenames: false
        always_run: true
    - repo: https://github.com/PyCQA/pydocstyle
      rev: '5.1.1'
      hooks:
        - id: pydocstyle
          name: pydocstyle
          entry: pydocstyle mkdocstrings_sourcelink
          language: system
          pass_filenames: false
          always_run: true
